version: "3.9"
services:
  first-solution-data:
    image: postgres:latest
    environment:
      POSTGRES_USER: FIRST_SOLUTION
      POSTGRES_PASSWORD: FIRST_SOLUTION
      POSTGRES_DB: FIRST_SOLUTION
      PGDATA: "/var/lib/postgresql/data/docker-data/first-solution-data"
    ports:
      - "5401:5432"
    volumes:
      - .:/var/lib/postgresql/data